/**
 * World & Physics Constants
 */
export const WORLD_CONFIG = {
  TILE_SIZE_RAW: 32,
  TILE_SIZE_VIRTUAL: 64,
  TILE_SCALE: 2,

  MOVEMENT_SPEED: 5,
  INTERACTION_RANGE: 64,
  PROXIMITY_RANGE: 120,

  PLAYER_SPAWN_X: 1600,
  PLAYER_SPAWN_Y: 1600,
};

/**
 * GID mapping constants (from Serene Village & Interiors)
 */
export const TILESET_CONFIG = {
  SERENE_VILLAGE_FIRST_GID: 392,
  INTERIORS_FIRST_GID: 1247,
  ROOM_BUILDER_COLS: 17,
  SERENE_VILLAGE_COLS: 19,
  INTERIORS_COLS: 16,
};
