@startuml AuthOverview
skinparam actorStyle stickman

actor "User" as U

package "Authentication Module" {
    usecase "Register Account" as UC_Reg
    usecase "Login Account" as UC_Log
    usecase "Google Authentication" as UC_G
    usecase "OTP Authentication" as UC_OTP
}

U -- UC_Reg
U -- UC_Log
UC_Reg ..> UC_G : <<include>>
UC_Reg ..> UC_OTP : <<include>>
UC_Log ..> UC_G : <<include>>
UC_Log ..> UC_OTP : <<include>>

@enduml
