@startuml
skinparam actorStyle stickman

actor "User" as U

rectangle "User change personal information" {
    usecase "Change personal information" as UC_Main
    usecase "Login" as UC_Login
    usecase "Change information" as UC_Info
    usecase "Change password" as UC_Pass
    
    U -- UC_Main
    UC_Main ..> UC_Login : <<include>>
    UC_Info ..> UC_Main : <<extend>>
    UC_Pass ..> UC_Main : <<extend>>
}

@enduml
